name: phone_ide
description: PhoneIDE is a highly dynamic IDE for learning on freeCodeCamp's mobile app.
version: 1.1.0+1
repository: https://github.com/freeCodeCamp/PhoneIDE
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.13
  highlight: ^0.7.0
  flutter_highlight: ^0.7.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  lints: ^1.0.1
flutter:
  uses-material-design: true
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf